### ISSUE TITLE
`ImageSlidingGallery` does not retain fixed dimension across all hosted images while being fluid in its bound

### ISSUE THREAD

**Issue by tetrachrome** [tetrachrome/chewbaaka#95]
`ImageSlidingGallery` currently does not retain fixed dimension across all hosted images.

For example, in the 'Schools, Teachers, Learners' subsection in the Ecology page, the instance of `ImageSlidingGallery` has a different dimension on the third image compared to the rest. See screenshots below.

<img width="1280" alt="ImageSlidingGallery_Issue_03" src="https://user-images.githubusercontent.com/554685/89187970-da9d5500-d552-11ea-8a8d-704bda92a956.png">

<img width="1280" alt="ImageSlidingGallery_Issue_04" src="https://user-images.githubusercontent.com/554685/89187985-de30dc00-d552-11ea-96a3-46f51f7aec7c.png">

This results in the prev/next buttons not vertically centered as expected, and also potentially causes stretching on page content (or "page jump").

----

Reproducible since version: `v0.1.2`

Screenshot taken on **MacBook Pro (Retina, 13-inch, Mid 2014)**.

Display resolution: `2560 x 1600`

OS version:

```
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G6020
```

Firefox version : `79.0 (64-bit)`

**Comment by gitsitgo** [comment]
I tried a solution which is to put in the gallery css class:
    height: 320px;
    object-fit: cover;

It sets a fixed bound, but the result is that picture size will not bump the page up and down, nor the controls, and the images can be of difference sizes. Does this work?
