### ISSUE TITLE
Scientific names should have the proper formatting

### ISSUE THREAD

**Issue by tetrachrome** [tetrachrome/chewbaaka#97]
References of scientific names of binomial nomenclature should have the proper formatting, including italiced font format. This rule should apply to all instances of such references.

An example of this currently does not apply is the intro section paragraph in the Biology page. See screenshot below:

<img width="1280" alt="TaxonomyName_Issue" src="https://user-images.githubusercontent.com/554685/89190538-78465380-d556-11ea-8503-47c639eb018b.png">

In this section, the words `"Acinonyx"` and `"jubatus"` should be at least italics, as they refer to a particular taxonomical name.

----

Reproducible since version: `v0.1.0`

Screenshot taken on **MacBook Pro (Retina, 13-inch, Mid 2014)**.

Display resolution: `2560 x 1600`

OS version:

```
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G6020
```

Firefox version : `79.0 (64-bit)`

**Comment by gitsitgo** [comment]
Working on it, got a fix, but will need CFU's help. :)
